export { GET_DATE_STATE } from './cafeteria/date.quries'
export { GET_MENU } from './cafeteria/menu.quries'
export { GET_CAFETERIA_NAME_STATE } from './cafeteria/name.quries'
export { GET_LOCATION_STATE } from './restaurant/location.quries'
export { GET_RESTAURANTS, GET_ALL_RESTAURANTS } from './restaurant/restaurants.quries'
